# Generated by Django 5.1.1 on 2024-10-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients_SobralPalacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fantasy_name_client", models.CharField(max_length=40)),
                ("code_client", models.IntegerField()),
            ],
        ),
    ]
