# Generated by Django 5.1.2 on 2024-10-10 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_driver', models.CharField(max_length=30)),
                ('business_line', models.CharField(max_length=30)),
                ('cpf_driver', models.CharField(max_length=11)),
                ('rg_driver', models.CharField(max_length=11)),
                ('rg_issuer', models.DateField()),
                ('driver_license', models.IntegerField()),
                ('category', models.CharField(max_length=1)),
                ('driver_license_issuer', models.DateField()),
                ('place_of_birth', models.DateField()),
                ('fone_driver', models.CharField(max_length=11)),
                ('email_driver', models.EmailField(max_length=50)),
                ('pis_driver', models.CharField(max_length=14)),
                ('gas_station_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.clients_sobralpalacio')),
            ],
        ),
    ]
