# Generated by Django 5.1.2 on 2024-10-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_driverlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gas_Station_SobralPalacio',
            fields=[
                ('fantasy_name_gas_station', models.CharField(max_length=40)),
                ('cnpj_gas_station', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='driverlist',
            name='gas_station_code',
        ),
        migrations.RemoveField(
            model_name='driverlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='driverlist',
            name='cpf_driver',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='driverlist',
            name='driver_license',
            field=models.CharField(max_length=11),
        ),
        migrations.AddField(
            model_name='driverlist',
            name='gas_station_CNPJ',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='register.gas_station_sobralpalacio'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Clients_SobralPalacio',
        ),
    ]
